---
name: "LQ Download"
guid: "8cdb7e71-66fc-42e1-b821-c37cab2451b6"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Transcode new media automatically for low quality downloads."
description: >
  When downloading to a client with limited storage, it's often
	desirable to have a lower quality file to save space. For
	example, on mobile devices. Very large files like 4k movies
	and shows can take up a lot of space. This plugin will
	automatically transcode new media into lower quality files
	available for download.
category: "General"
owner: "calebvetter"
artifacts:
- "Jellyfin.Plugin.LQDownload.dll"
changelog: >
  changelog
